INSERT INTO `FoodSet`
VALUES
('Com Ga'),
('Pho Bo'),
('Chao Suon'),
('My Van Than'),
('Bun Bo Nam Bo'),
('Pho Ga'),
('Lau ech'),
('Com Tron Han Quoc'),
('Banh Xeo'),
('Khoai Tay Nghien'),
('Thit Bo Luc Lac'),
('Banh Trung'),
('Xoi Ga'),
('Xoi Thit Kho'),
('Bun Cha'),
('Lau Thai'),
('Banh Pizza'),
('Bun Thang'),
('Sushi'),
('Pho Mai Que'),
('Ga Ham Thuoc Bac'),
('Com Rang Hai San'),
('Banh Humberger'),
('Lau Nuong'),
('Lau Nam'),
('Gia Cay'),
('Kimchi'),
('Bun Ca Hai Phong'),
('Pho Cuon'),
('Chao Trai'),
('Mien Tron'),
('Khoai Tay Chien'),
('Nem Chua'),
('Banh My Sandwich'),
('Tobuki'),
('Salad Nga'),
('Nem Uyen Uong'),
('Tra Sua Chan Chau'),
('Cocktail'),
('Cha Ruoi'),
('Cao Lau'),
('Vit Quay Bac Kinh'),
('Ngan Om Sau'),
('Chao Ga'),
('Pho Xao'),
('Chao Ca'),
('Chan Gio Hun Kho');